git:
  submodules: true
language: scala
# run on new infrastructure
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin
    CHISEL3=3.1.0
    CHISEL_TESTERS=1.2.0

install:
  # Install dependencies
  - bash .install_verilator.sh
  - verilator --version
  - bash .install_rocketchip.sh

script:
  - make test rocket-test

